version: '3.3'
services:
  icecast:
    container_name: icecast
    image: $IMAGE_REPO
    volumes:
      - $DATA_BASE_PATH/icecast/icecast.xml:/etc/icecast.xml
    restart: unless-stopped
    env_file:
      - stack.env

networks:
  default:
    external:
      name: shared