version: '3.6'

services:
  flame:
    image: pawelmalak/flame:multiarch
    container_name: flame
    volumes:
      - $DATA_BASE_PATH/flame/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    #ports:
    #  - 5005:5005
    secrets:
      - password # optional but required for (1)
    environment:
      - PGID
      - PUID
      - PASSWORD_FILE
#     - PASSWORD_FILE=/run/secrets/password # optional but required for (1)
    restart: unless-stopped
    labels:
      - flame.type=app # "app" works too
      - flame.name=flame
      - flame.url=$FLAME_URL
      #- flame.icon=icon-name # optional, default is "docker"
      #- flame.icon=custom to make changes in app. ie: custom icon upload
networks:
  default:
    external:
      name: shared
# optional but required for Docker secrets (1)
secrets:
  password:
    file: $DATA_BASE_PATH/compose/flame/password