version: "3.3"
services:
  alpine-qbittorrent-openvpn:
    #image: guillaumedsde/alpine-qbittorrent-openvpn:latest
    image: $IMAGE_REPO
    volumes:
      - /media/Library/Downloads:/downloads
      - $DATA_BASE_PATH/qbittorrent-openvpn/config:/config
      - /media/Library/Videos:/videos
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID
      - PGID
      - OPENVPN_PROVIDER
      - OPENVPN_CONFIG
      - OPENVPN_USERNAME
      - OPENVPN_PASSWORD
      - LAN
      - TZ
      - LOG_TO_STDOUT
      - QBT_WEBUI_PORT
    cap_add:
      - NET_ADMIN
    #ports:
    #  - "8282:8282"

networks:
  default:
    external:
      name: shared