version: '3.3'
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle
    ports:
      - 8888:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "bridge"