# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3.3'
services:
  mediawiki:
    networks:
      - proxy-traefik
    image: mediawiki
    restart: unless-stopped
    ports:
      - 8080:80
    links:
      - database
    volumes:
      - images:/var/www/html/images
      - extensions:/var/www/html/extensions
      - assets:/var/www/html/assets
      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php
  # This key also defines the name of the database host used during setup instead of the default "localhost"
  database:
    image: mariadb
    restart: always
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    volumes:
      - db:/var/lib/mysql
networks:
  shared:
    external:
      name: shared
volumes:
  images:
  db:
  extensions:
  assets: