name: Portainer Redeployments
on:
  push:
    branches:
      - 'main'
      - 'ice'
      - 'ice-test'
jobs:
  Redeploy-Portainer-Stacks:
    runs-on: ubuntu-latest
    steps:
    -
      name: icecast
      uses: ./.github/fast-webhook
      with:
        url: ${{ secrets.ICECAST_WEBHOOK_URL }}