name: Portainer Redeployments
on:
  push:
    branches:
      - 'main'

jobs:
  Redeploy-Portainer-Stacks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    -
      name: icecast
      uses: ./.github/actions/fast-webhook
      with:
        url: ${{ secrets.ICECAST_WEBHOOK_URL }}