name: Portainer Redeployments
on:
  push:
    branches:
      - 'main'
      - 'ice'
      - 'ice-patch-1'
jobs:
  Redeploy-Portainer-Stacks:
    runs-on: ubuntu-latest
    steps:
    -
      name: icecast
      uses: JrdnRgrs/fast-webhook@v1
      with:
        url: ${{ secrets.ICECAST_WEBHOOK_URL }}
