version: '3.3'
services:
  samba:
    container_name: samba
    image: dperson/samba:latest
    network_mode: "host"
    ports:
      - 139:139
      - 445:445
      - 137:137/udp
      - 138:138/udp
    volumes:
      - /media/Library:/share
      - samba_logs:/var/lib/samba
      - samba_libs:/var/log/samba
      - samba_etc:/etc
      - samba_run:/run/samba
      - samba_cache:/var/cache/samba
    environment:
      - GROUPID
      - USERID
      - PGID
      - PUID
      - PERMISSIONS
      - TZ
      - USER
      - SHARE
      - NMBD
      - RECYCLE
      - WIDELINKS
    tty: true

volumes:
  samba_logs:
  samba_libs:
  samba_etc:
  samba_run:
  samba_cache: